# Generated by Django 4.0.3 on 2022-08-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technicin',
            new_name='Technician',
        ),
    ]
