# Generated by Django 4.0.3 on 2022-08-02 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_technician_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assigned_tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service_rest.technician'),
        ),
    ]
