# Generated by Django 4.0.3 on 2022-08-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_remove_automobilesvo_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Scheduled', max_length=30),
        ),
    ]
