# Generated by Django 4.0.3 on 2022-08-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed',
            field=models.BooleanField(default=False, max_length=30),
        ),
    ]
