# Generated by Django 4.0.3 on 2022-08-04 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_remove_appointment_status_appointment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assigned_tech',
            field=models.ForeignKey(default='Unassigned', on_delete=django.db.models.deletion.SET_DEFAULT, to='service_rest.technician'),
        ),
    ]
