# Generated by Django 4.0.3 on 2022-08-04 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_alter_appointment_assigned_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assigned_tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_rest.technician'),
        ),
    ]
