# Generated by Django 4.0.3 on 2022-08-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_alter_appointment_assigned_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assigned_tech',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.PROTECT, to='service_rest.technician'),
            preserve_default=False,
        ),
    ]
